"""addew new things

Revision ID: de7085077dd6
Revises: d5be30353430
Create Date: 2025-12-07 22:58:24.755237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7085077dd6'
down_revision: Union[str, Sequence[str], None] = 'd5be30353430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'vendors', ['email'], unique=True)
    # ### end Alembic commands ###
